# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FtpAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('allowed', models.CharField(blank=True, max_length=254, null=True)),
                ('denied', models.CharField(blank=True, max_length=254, null=True)),
                ('options', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ('name', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FtpGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('gid', models.PositiveIntegerField()),
                ('members', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ('name', 'gid', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='FtpUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='name')),
                ('password', models.CharField(max_length=128, verbose_name='login')),
                ('home', models.CharField(max_length=256, verbose_name='home')),
                ('uid', models.PositiveIntegerField(unique=True, verbose_name='uid')),
                ('gid', models.PositiveIntegerField(unique=True, verbose_name='uid')),
                ('shell', models.CharField(default='/usr/sbin/nologin', max_length=256, verbose_name='shell')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user', 'name', '-created_at'),
                'verbose_name_plural': 'ftp users',
                'verbose_name': 'ftp user',
            },
        ),
    ]
